### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by Tilogorn** [jfcherng/php-diff#1]
Hi Jack,

as you are the most active developer and you have a very good implementation of php-diff we are using your diff solution in production.

We are using php-diff since November 2018 in Version 2.1.17. I just noticed via composer that you now reached version 4.0.1 and published **23 new releases since**. I love updates but for dependency maintenance it's quite a challenge ;-)

As I can not tell if you use semantic versioning ([semver](https://semver.org/)) I am afraid to update because updating from v2 to v4 means often breaking changes. 

It would help a lot if you would add a changelog to your releases (or to the README) and/or use semantic versioning (so I know I can safely update from e.g. 2.1 to 2.9).

Kind regards and a big thanks for your good work!

**Comment by jfcherng** [comment]
Yes, I plan this package to follow semver. `patch` = bug fix, `minor` = new feature, `major` = BC break.

Those BC breaks are tiny though. I add some upgrading guides in the readme now.
https://github.com/jfcherng/php-diff/tree/master/UPGRADING

Feel free to ask questions if you find something weird or missing in the docs.

**Comment by Tilogorn** [comment]
Perfect, thanks a lot!
