### ISSUE TITLE
How to return some text when both strings are identicals?

### ISSUE THREAD

**Issue by sdlins** [jfcherng/php-diff#12]
Hi,

First of all, thank you for your efforts to make/continue this extension. But I have a question: I found `RendererInterface::getResultForIdenticals()` but in `SideBySide` implementation it returns a `''` empty string, `SideBySide` is a `final` class so that I can't extend it, so, how could I set a string to show for equal situations?

**Comment by jfcherng** [comment]
Those `final`s are added to reduce unnecessary possible BC breaks if someone (such as me) changes class implementations or even simply renames a method.

Maybe you can just use a function to wrap it?

```php
function renderDiffer(RendererInterface $renderer, Differ $differ): string
{
    $diff = $renderer->render($differ);

    if (\is_a($renderer, SideBySide::class) && $diff === '') {
        $diff = 'There is no difference.';
    }

    return $diff;
}
```

Or copy the `SideBySide` implementation to another class and modify it to what you want. (namely, create your own renderer)

**Comment by sdlins** [comment]
@jfcherng thank you. I had not thought about a function. I had only thought to "duplicate" SideBySide implementation just to change that method but, both function and duplication it seems very cumbersome (dont get me wrong) since we already have the method but returning nothing. 

I propose to implement the string to be returned as a configurable option.

**Comment by jfcherng** [comment]
Added. Could you test it with the renderer option `resultForIdenticals` with the current `v6` branch to see if I miss/misunderstand something?

```php
// the renderer class options
$rendererOptions = [
    // change this value to a string as the returned diff if the two input strings are identical
    'resultForIdenticals' => null,
];
```

**Comment by sdlins** [comment]
Nice... Worked fine! Thank you.

**Comment by jfcherng** [comment]
`6.2.0` has been released now. :)
