### ISSUE TITLE
Render HTML from JSON

### ISSUE THREAD

**Issue by hasan-ozbey** [jfcherng/php-diff#16]
it could be good option to store differences as JSON in database and then convert them into tabular view.

**Comment by jfcherng** [comment]
There is the JSON renderer https://github.com/jfcherng/php-diff#renderer-json. I don't have an experience on tabular view. The meaning of `tag` numbers are defined in https://github.com/jfcherng/php-sequence-matcher/blob/06e953/src/SequenceMatcher.php#L16-L20 if you set the renderer option `'outputTagAsString' => false,`.

**Comment by hasan-ozbey** [comment]
No no, i'm talking about **converting** JSON renderer's output to Inline (HTML) renderer's output.

**Comment by jfcherng** [comment]
Closed since #17 has been merged.
