### ISSUE TITLE
PSR2

### ISSUE THREAD

**Issue by JBlond** [jfcherng/php-diff#2]
There are some code violations to PSR2

You use phpcs.xml with 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ruleset name="php-diff">
	<description>php-diff</description>
	<rule ref="PSR2" />
</ruleset>
```
example
```bash
php phpcs.phar --standard=phpcs.xml -s -p --colors ./src/
```

**Comment by jfcherng** [comment]
!! 

I thought php-cs-fixer would take care that for me with proper settings. But I looks like it doesn't. Thanks for showing me this.

It looks like all errors are about my multi-condition `if` style like
![image](https://user-images.githubusercontent.com/6594915/53097073-8ddedd80-355b-11e9-8576-bc7a3b892869.png)

Should be easy fix. :+1:

**Comment by JBlond** [comment]
```
.W....E....E..W.....E.. 23 / 23 (100%)



\src\DiffHelper.php
--------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
--------------------------------------------------------------------------------------------------------
 87 | WARNING | Line exceeds 120 characters; contains 140 characters (Generic.Files.LineLength.TooLong)
--------------------------------------------------------------------------------------------------------


\src\Renderer\Html\AbstractHtml.php
-------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 3 LINES
-------------------------------------------------------------------------------------------------------------------------------------------------
  63 | ERROR | [x] Expected 0 spaces after opening bracket; newline found (PSR2.ControlStructures.ControlStructureSpacing.SpacingAfterOpenBrace)
 100 | ERROR | [x] Expected 0 spaces after opening bracket; newline found (PSR2.ControlStructures.ControlStructureSpacing.SpacingAfterOpenBrace)
 115 | ERROR | [x] Expected 0 spaces after opening bracket; newline found (PSR2.ControlStructures.ControlStructureSpacing.SpacingAfterOpenBrace)
-------------------------------------------------------------------------------------------------------------------------------------------------
PHPCBF CAN FIX THE 3 MARKED SNIFF VIOLATIONS AUTOMATICALLY
-------------------------------------------------------------------------------------------------------------------------------------------------


\src\Renderer\Html\LineRenderer\Line.php
------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
------------------------------------------------------------------------------------------------------------------------------------------------
 60 | ERROR | [x] Expected 0 spaces after opening bracket; newline found (PSR2.ControlStructures.ControlStructureSpacing.SpacingAfterOpenBrace)
 70 | ERROR | [x] Expected 0 spaces after opening bracket; newline found (PSR2.ControlStructures.ControlStructureSpacing.SpacingAfterOpenBrace)
------------------------------------------------------------------------------------------------------------------------------------------------
PHPCBF CAN FIX THE 2 MARKED SNIFF VIOLATIONS AUTOMATICALLY
------------------------------------------------------------------------------------------------------------------------------------------------


\src\Renderer\Html\LineRenderer\Word.php
--------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
--------------------------------------------------------------------------------------------------------
 34 | WARNING | Line exceeds 120 characters; contains 127 characters (Generic.Files.LineLength.TooLong)
--------------------------------------------------------------------------------------------------------


\src\Renderer\Text\Unified.php
------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
------------------------------------------------------------------------------------------------------------------------------------------------
 51 | ERROR | [x] Expected 0 spaces after opening bracket; newline found (PSR2.ControlStructures.ControlStructureSpacing.SpacingAfterOpenBrace)
 58 | ERROR | [x] Expected 0 spaces after opening bracket; newline found (PSR2.ControlStructures.ControlStructureSpacing.SpacingAfterOpenBrace)
```

**Comment by jfcherng** [comment]
# [PSR-2 overview](https://www.php-fig.org/psr/psr-2/#1-overview)


## Expected 0 spaces after opening bracket

It turns out to be there are [many people](https://github.com/squizlabs/PHP_CodeSniffer/issues/460) using PHPCS having questions about the `Opening parentheses for control structures MUST NOT have a space after them, and closing parentheses for control structures MUST NOT have a space before.` rule as stated in the PSR-2. What's the term "space"  exactly means?

After the following readings, I currently decide NOT to change my coding style about multiline `if`s since I think it's more readable (well, personally). Or, what's the correct coding style for the following multiline `if` if you must write them in multilines?

```php
if (
    $a &&
    $b &&
    $c &&
    $d 
) {
    // ...
}
```

I don't think the following one is more readable, seriously.

```php
if ($a &&
    $b &&
    $c &&
    $d) {
    // ...
}
```


### References

- https://github.com/squizlabs/PHP_CodeSniffer/issues/460#issuecomment-94318715 (especially)
- https://github.com/squizlabs/PHP_CodeSniffer/issues/1829
- https://github.com/squizlabs/PHP_CodeSniffer/pull/188


## Line exceeds 120 characters

They are indeed too long because they evolves long URLs in comments.

PSR-2 states `There MUST NOT be a hard limit on line length; the soft limit MUST be 120 characters; lines SHOULD be 80 characters or less.`. There is no hard limit on line length so it's fine but I am willing to fix them if it's easy (and not ugly).

**Comment by jfcherng** [comment]
Thanks for bringing phpcs.

- Introduce phpcs: https://github.com/jfcherng/php-diff/commit/86f232519f7907808019d3e776b308068ff30a67
- Fix a 120 chars per line: https://github.com/jfcherng/php-diff/commit/42eeff7fac561173f48a1063dded61f79ed2c167

**Comment by JBlond** [comment]
The one in \src\Renderer\Html\LineRenderer\Word.php line 34 is left ;) 7 characters too long. But I can live with that.

**Comment by JBlond** [comment]
The rule that you excluded could like in Unified.php Could be fixed like

```php
 if ($tag === SequenceMatcher::OP_REP ||
                    $tag === SequenceMatcher::OP_DEL
                ) {
                    $ret .= $this->renderContext('-', $this->diff->getA($i1, $i2));
                }

                if ($tag === SequenceMatcher::OP_REP ||
                    $tag === SequenceMatcher::OP_INS
                ) {
                    $ret .= $this->renderContext('+', $this->diff->getB($j1, $j2));
                }
```

**Comment by JBlond** [comment]
![psr2](https://user-images.githubusercontent.com/2391810/53104147-1eeb8f80-352f-11e9-8d16-335e52f3f332.png)

**Comment by jfcherng** [comment]
But it doesn't make sense.

PSR-2 states "Opening parentheses for control structures MUST NOT have a space after them, and *closing parentheses for control structures MUST NOT have a space before*."

![image](https://user-images.githubusercontent.com/6594915/53105030-5710c380-356b-11e9-925d-900d01b20e16.png)
In your screenshot, if it's not allowed for a opening parenthesis, why it's "okay now" for a closing parentheses?

**Comment by JBlond** [comment]
Because the first condition after the **(** bracket, there is no space. **if ($tag** expected.. While
**if ([EVIL_SPACE OR RETURN]$tag** is not correct.

**Comment by jfcherng** [comment]
I could accept that the opening bracket is evil.
But in that case, isn't the following evil too if spaces before a **closing** bracket is not allowed?
![image](https://user-images.githubusercontent.com/6594915/53107960-2764ba00-3571-11e9-8775-453c41996664.png)

**Comment by JBlond** [comment]
That is okay, I tested it against the phpcs.xml without the excluded rule. Not saying that it is understandable.

**Comment by jfcherng** [comment]
That is a weird one that causing so many people having problems on it unfortunately :/

Thanks god that `if (` is 4-char which is the same of a indentation.
But not that fortunate for `while (`.

```php
while ($a &&
    $b &&
    $c
) {
    // ...
}
```

is just ugly.

**Comment by JBlond** [comment]
PSR is not the only way to format code ;)

```bash
./vendor/bin/phpcs -i
The installed coding standards are MySource, PEAR, PSR1, PSR12, PSR2, Squiz and Zend
```

**Comment by jfcherng** [comment]
PSR-12 is not accepted yet.
But a good thing to know is https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md#51-if-elseif-else. :+1: 

I wish I could follow PSR as much as possible since it's the most well-known currently.
Unofficial though.

**Comment by JBlond** [comment]
@jfcherng it could be worse :D

![worse](https://external-preview.redd.it/P1B98VFlL6po1QqQRepzJc0O7npbCjUAZTGPh4Leh3A.png?auto=webp&s=de0b625451dca744131e9ede0af65ec858e8580b)

**Comment by jfcherng** [comment]
I dont think your screenshot could even pass PSR-2.

Any way, my codes would pass PSR-12's multiline `if` and that's enough.
People who want to make PRs with codes like the your screenshot would not be accepted here.
As for other people's libraries, not my business.

**Comment by JBlond** [comment]
For sure is doen't pass PSR2, it was a joke.

**Comment by jfcherng** [comment]
Just a FYI. PSR-12 is adopted now, which resolves the argument in this issue.
