### ISSUE TITLE
Feedbacks for SideBySide Renderer

### ISSUE THREAD

**Issue by hasan-ozbey** [jfcherng/php-diff#21]
I'm getting some feedbacks from users for SideBySide Renderer.

We should merge two equal lines and expand the changed lines over the blank ones on SideBySide Renderer when `lineNumbers` option set to `false` because it makes more sense and looks beautiful that way. See samples:

## What's now:

![now](https://i.ibb.co/vPpG3rb/noww.png)

## What should be:

![new](https://i.ibb.co/Hp0rDGW/thennnn.png)

Besides, please consider flexbox for v7.

**Comment by jfcherng** [comment]
Without line numbers, the current output is not able to be visually distinguished between "delete old lines" and "replace with empty new lines". Merging output like your example looks good to me.

**Comment by jfcherng** [comment]
Should have been done in `6.4.3`. Feel free to reopen if the problem persists.

**Comment by hasan-ozbey** [comment]
Well, it looks okay for now. Thanks for this repo btw, i really appreciate your work!

**Comment by jfcherng** [comment]
By the way, I am fine with flexbox (and I think it's good to do it, especially now Microsoft drops IE so modern CSS can be more widely used). But I currently have no strong motivation to do it since this repo works well for myself now.
