### ISSUE TITLE
Custom html

### ISSUE THREAD

**Issue by Wulfheart** [jfcherng/php-diff#31]
Hello,

is it possible to inject custom html for a custom design?

**Comment by jfcherng** [comment]
No. It requires you to implement your own renderer, i.e., https://github.com/jfcherng/php-diff/blob/v6/src/Renderer/RendererInterface.php. Or use other PHP HTML libs to manipulate the generated HTML.

---

Or, use the renderer JSON to render DOMs in the frontend via JS.

**Comment by jfcherng** [comment]
Close because of inactivity.
