### ISSUE TITLE
Difference of the Diffing Libraries

### ISSUE THREAD

**Issue by mustafa519** [jfcherng/php-diff#37]
Hello,

I'm trying to implement the **diffing logic** on my project. I've been searched for diffing library for requirements of my project.

I've found two useful library. Yours and [yetanotherape/diff-match-patch](https://github.com/yetanotherape/diff-match-patch). Could you give me details that what is the difference between these libraries actually?

I could tell that the other library has support patch and different search algorithm. But also it hasn't provide HTML output. Your library so flexible for HTML output.

Also the other library has new line diffing match. I mean the library could able to catch the same sentence even the line has increased. As if it would be amazing that you could use the core algorithm of the other library on your project. But i might have missed something that i have don't know yet. Also that's why i've opened the issue.

I just don't want to miss something before having bad experience that if i choose yours or the other library for my requirement.

Thank you for providing the library to the community.

**Comment by jfcherng** [comment]
Unfortunately, I am not a diff algo guru so I can't actually answer detailed diff algo things and I didn't research `yetanotherape/diff-match-patch` either. This repo (actually [jfcherng/php-sequence-matcher](https://github.com/jfcherng/php-sequence-matcher)) is more of a plain porting of the official [Python's diff module](https://docs.python.org/3/library/difflib.html) + some pre-written renderers. 

I think as long as you have a correct diff, it's up to you how you want it to be rendered regardless whatever lib you use. That says if you feel the result from `yetanotherape/diff-match-patch` meets your need better, it should be feasible to render

```php
array(
    array(DiffMatchPatch::DIFF_EQUAL, "Th"),
    array(DiffMatchPatch::DIFF_DELETE, "e"),
    array(DiffMatchPatch::DIFF_INSERT, "at"),
    array(DiffMatchPatch::DIFF_EQUAL, " quick brown fox jump"),
    array(DiffMatchPatch::DIFF_DELETE, "s"),
    array(DiffMatchPatch::DIFF_INSERT, "ed"),
    array(DiffMatchPatch::DIFF_EQUAL, " over "),
    array(DiffMatchPatch::DIFF_DELETE, "the"),
    array(DiffMatchPatch::DIFF_INSERT, "a"),
    array(DiffMatchPatch::DIFF_EQUAL, " lazy dog."),
)
```

into whatever you want it to be looked like.

---

This repo has no patch functionality indeed and I don't need it so it's very likely I won't do it but PRs welcome :P

**Comment by mustafa519** [comment]
Oh it's okay, i'm also not guru of the algorithms or something like that. I really liked your library and your logic. I've already starred your project before use.

The PR(to merge those libraries) would completely change of the core of your library.

But it would be amazing to mix the libraries.

I will try to implement detailed the HTML output with the other library by standalone. And if you are willing to change the core of this library, i'd like to send PR after that. However, also you'll need to implement your renderer and output settings.

Otherwise, if you are okay without supporting the other benefits, it's okay. You did very well already.

Thank you for fast response.
