### ISSUE TITLE
Error with "$new" is empty

### ISSUE THREAD

**Issue by artem-brezutsky** [jfcherng/php-diff#38]
Hello, I am getting an error when the variable "$new" comes up empty. Is there any way to fix this?

`
        $rendererName = "Combined";

        $differOptions = [
            'context' => 3,
            'ignoreCase' => false,
            'ignoreWhitespace' => true,
        ];

        $rendererOptions = [
            'detailLevel' => 'char',
            'language' => 'rus',
            'lineNumbers' => false,
            'separateBlock' => true,
            'spacesToNbsp' => false,
            'tabSize' => 4,
            'mergeThreshold' => 0.8,
            'resultForIdenticals' => null,
            'wrapperClasses' => ['diff-wrapper'],
        ];
`

`File: /var/www/gomer.local/www/vendor/jfcherng/php-sequence-matcher/src/SequenceMatcher.php
Line: 244
#0 /var/www/gomer.local/www/vendor/jfcherng/php-sequence-matcher/src/SequenceMatcher.php(244): yii\base\ErrorHandler->handleError(8, 'Undefined offse...', '/var/www/gomer....', 244, Array)
#1 /var/www/gomer.local/www/vendor/jfcherng/php-sequence-matcher/src/SequenceMatcher.php(337): Jfcherng\Diff\SequenceMatcher->findLongestMatch(0, 4, 0, 0)
#2 /var/www/gomer.local/www/vendor/jfcherng/php-sequence-matcher/src/SequenceMatcher.php(426): Jfcherng\Diff\SequenceMatcher->getMatchingBlocks()
#3 /var/www/gomer.local/www/vendor/jfcherng/php-diff/src/Renderer/Html/LineRenderer/AbstractLineRenderer.php(103): Jfcherng\Diff\SequenceMatcher->getOpcodes()
#4 /var/www/gomer.local/www/vendor/jfcherng/php-diff/src/Renderer/Html/LineRenderer/Char.php(21): Jfcherng\Diff\Renderer\Html\LineRenderer\AbstractLineRenderer->getChangedExtentSegments(Array, Array)
#5 /var/www/gomer.local/www/vendor/jfcherng/php-diff/src/Renderer/Html/AbstractHtml.php(156): Jfcherng\Diff\Renderer\Html\LineRenderer\Char->render(Object(Jfcherng\Utility\MbString), Object(Jfcherng\Utility\MbString))
#6 /var/www/gomer.local/www/vendor/jfcherng/php-diff/src/Renderer/Html/AbstractHtml.php(89): Jfcherng\Diff\Renderer\Html\AbstractHtml->renderChangedExtent(Object(Jfcherng\Diff\Renderer\Html\LineRenderer\Char), '1234', '')
#7 /var/www/gomer.local/www/vendor/jfcherng/php-diff/src/Renderer/Html/AbstractHtml.php(113): Jfcherng\Diff\Renderer\Html\AbstractHtml->getChanges(Object(Jfcherng\Diff\Differ))
#8 /var/www/gomer.local/www/vendor/jfcherng/php-diff/src/Renderer/AbstractRenderer.php(172): Jfcherng\Diff\Renderer\Html\AbstractHtml->renderWorker(Object(Jfcherng\Diff\Differ))
#9 /var/www/gomer.local/www/vendor/jfcherng/php-diff/src/DiffHelper.php(134): Jfcherng\Diff\Renderer\AbstractRenderer->render(Object(Jfcherng\Diff\Differ))
#10 /var/www/gomer.local/www/vendor/splitter-modules/market.gomer/common/helpers/StringHelper.php(161): Jfcherng\Diff\DiffHelper::calculate(Array, Array, 'Combined', Array, Array)
#11 /var/www/gomer.local/www/vendor/splitter-modules/market.gomer/controllers/ItemsController.php(562): market\gomer\common\helpers\StringHelper::descriptionDiff('&lt;style&gt; ....', '')
#12 [internal function]: market\gomer\controllers\ItemsController->actionShowDiff()
#13 /var/www/gomer.local/www/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#14 /var/www/gomer.local/www/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#15 /var/www/gomer.local/www/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('show-diff', Array)
#16 /var/www/gomer.local/www/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('gomer/items/sho...', Array)
#17 /var/www/gomer.local/www/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#18 /var/www/gomer.local/www/backend/web/index.php(22): yii\base\Application->run()
#19 {main}`

**Comment by jfcherng** [comment]
I am able to get some "undfined offset" with
```php
$old = '123';
$new = '';
```

**Comment by artem-brezutsky** [comment]
Can you fix this in future updates?

**Comment by jfcherng** [comment]
Very likely yes but I am not available at this moment.

**Comment by jfcherng** [comment]
Hi, I've fixed a potentially related issue on the upstream ( [jfcherng/php-sequence-matcher](https://github.com/jfcherng/php-sequence-matcher/releases/tag/3.2.6) `3.2.6` ).
Could you try to update the dependency and make sure `jfcherng/php-sequence-matcher` `3.2.6` be used?

**Comment by jfcherng** [comment]
Closed due to inactivity.
