### ISSUE TITLE
JSON renderer sometimes set <ins> and <del> tags into lines

### ISSUE THREAD

**Issue by phoenixgao** [jfcherng/php-diff#40]
This is an return value example I've got:

```json
[{
    "new": {
        "lines": ["菲灵", "Elmex", "夏依"],
        "offset": 0
    },
    "old": {
        "lines": ["菲灵", "Elmex", "夏依"],
        "offset": 0
    },
    "tag": "eq"
}, {
    "new": {
        "lines": ["<ins>福来恩</ins>"],
        "offset": 3
    },
    "old": {
        "lines": ["<del>百吉福</del>"],
        "offset": 3
    },
    "tag": "rep"
}, {
    "new": {
        "lines": ["乐高"],
        "offset": 4
    },
    "old": {
        "lines": ["乐高"],
        "offset": 4
    },
    "tag": "eq"
}, {
    "new": {
        "lines": [""],
        "offset": 5
    },
    "old": {
        "lines": ["天维美/国内"],
        "offset": 5
    },
    "tag": "del"
}, {
    "new": {
        "lines": ["皇家京东", "九木杂物社淘宝", "网鱼网咖", "味全", "英雄联盟旗舰店"],
        "offset": 5
    },
    "old": {
        "lines": ["皇家京东", "九木杂物社淘宝", "网鱼网咖", "味全", "英雄联盟旗舰店"],
        "offset": 6
    },
    "tag": "eq"
}]
```

with the following options:

```php
$diffJson = DiffHelper::calculate($old, $new, "Json",
            [
                'context' => 2048
            ],
            [
                'outputTagAsString' => true,
            ]
        );
```

**Comment by jfcherng** [comment]
`"lines"` are ALWAYS HTML contents. That is, `<>&"'` etc in the source text will be encoded/escaped.

If you want them to be plain text,

1. remove `<del>`, `</del>`, `<ins>`, `</ins>`
2. apply `htmlspecialchars_decode()`

by doing so, you lose inline detailed diff.

**Comment by phoenixgao** [comment]
@jfcherng my source text does not contain the tags, they were just plain text.

Could it be possible that it was added by the render because my 'detailLevel' is by default set to line?
I found that all the lines contains `<ins>` and `<del>` tags are in the blocks which tags are "rep"

**Comment by jfcherng** [comment]
> Could it be possible that it was added by the render because my 'detailLevel' is by default set to line?

That's exactly what `detailLevel` does... If you don't want it, you can set it to `"none"`. But still, you have better to check whether a `&` in the source text will be encoded into `&amp;` or not (I am not sure but I prefer yes).

---

In case you didn't see screenshots in the readme, I post it here for you for visualized explanation.
![image](https://user-images.githubusercontent.com/6594915/97541660-79c1d380-1a00-11eb-8a90-77c77c5bc09b.png)

Things between `<ins>` and `</ins>` is the deep green part. `<del>` and `</del>` are in deep red. What you are asking for is basically no detailed diff.

**Comment by phoenixgao** [comment]
@jfcherng OOh I thought Json renderer wouldn't compare at line/word level since in the readme it says that option is for html renderer. Thanks for detailed explanation, I'm closing this issue ;p

**Comment by jfcherng** [comment]
> @jfcherng OOh I thought Json renderer wouldn't compare at line/word level since in the readme it says that option is for html renderer. Thanks for detailed explanation, I'm closing this issue ;p

Due to historical reason, in the implementation, the JSON renderer is inherited from the HTML renderer (but the output is "text"). I think in order to let the output JSON be able to have detailed diff, using HTML in `"lines"` is a way.

So yeah... it's quite confusing that the JSON renderer is a text one or a HTML one...

**Comment by jfcherng** [comment]
But if you don't need any further detailed output or you want to deal with it in the frontend, I guess you can write a custom JSON renderer which simply dumps (`json_encode()`) those opcodes from the sequence matcher.

**Comment by jfcherng** [comment]
@phoenixgao This sounds like a valid yet simple renderer to have. I may do it tonight :+1:

**Comment by jfcherng** [comment]
@phoenixgao You may try the `JsonText` text renderer as of version `6.8.0`. Just change the renderer name from `Json` to `JsonText` in your case.
