### ISSUE TITLE
[Suggestion] Option to disable the header in HTML renderer

### ISSUE THREAD

**Issue by davidhirtz** [jfcherng/php-diff#42]
This looks really good, thank you for your work. Just a quick suggestion, would it be possible to add an option to disable the generation of the table header in `renderTableHeader()` in the HTML renderers? For now I'll just hide it via CSS.

Thanks again.

David

**Comment by jfcherng** [comment]
sounds good to me :)

**Comment by jfcherng** [comment]
`6.9.0` has been released with `showHeader` renderer option.
