### ISSUE TITLE
How to show statistic

### ISSUE THREAD

**Issue by molchanov1983** [jfcherng/php-diff#43]
Hello. 
I can not find a way how to get statistic.

Added - 5 lines, deleted - 10 lines, updated - 2 lines, unmodified - 250 lines

Is it possible to read it?

Also can not find a way how to show how many lines is hidden.
'context' => 3, => means how many lines to show before or after changes. 
But how to show "1001 Unmodified line(s)" no idea

Thanks

**Comment by jfcherng** [comment]
Sounds like a reasonable request to me.

Done in https://github.com/jfcherng/php-diff/commit/4b170cd79403a8723024eea3dfb62651735d0547 and [6.9.10](https://github.com/jfcherng/php-diff/releases/tag/6.10.0).
