### ISSUE TITLE
Json Combined

### ISSUE THREAD

**Issue by jack85811** [jfcherng/php-diff#44]
Hello!
first  of all thank you very much for this cool library. I've been playing around with it a lot today!
Although it offers a lot, i couldn't find an option to have what "Renderer: Combined" does with an JSON option.
"Renderer: HTML JSON" kind of does it but it would still out put a deleted and inserted item in the "new" and "old" table separately.
Are you aware of a feasible solution to have what you do with combined just as output like the "Renderer: HTML JSON"?

If that is not the case do you have a good idea on how to do that?

Kind Regards
Jack

**Comment by jfcherng** [comment]
> If that is not the case do you have a good idea on how to do that?

I think that basically need to create a new renderer. Some logic can be borrowed/reused from the `Combine` renderer... but that could still take some time.

**Comment by jack85811** [comment]
Okay! thanks for the input, maybe i might get around it by using the Combine Renderer.

Thanks!
