### ISSUE TITLE
Not same comparison result

### ISSUE THREAD

**Issue by japafrite** [jfcherng/php-diff#45]
Hello,
When I run example on my server (PHP Version 8.0.2), I don't get the same result. For example with Combined / Word :

![image](https://user-images.githubusercontent.com/49430437/125404742-428d2a00-e3b7-11eb-9fe3-dc01da6181e7.png)

Thanks for your help

Antoine

**Comment by jfcherng** [comment]
Did you change the settings to `'detailLevel' => 'word',`? Yours looks like the default, which is `line`.

**Comment by japafrite** [comment]
No and it's better if I change, just misunderstanding of the documentation.
Thanks
