### ISSUE TITLE
cant find vendor/autoload.php

### ISSUE THREAD

**Issue by unluckychild** [jfcherng/php-diff#47]
I downloaded and tried to open demo_base.php and everything in example, but shows error

**Comment by jfcherng** [comment]
1. read readme https://github.com/jfcherng/php-diff/tree/v6/example
2. tell what you have done
3. what's the error? telling shows error = telling nothing

**Comment by unluckychild** [comment]
is there a way to open the script without installing like any other php scripts?

**Comment by unluckychild** [comment]
i used yours few years ago and it worked fine until now

**Comment by jfcherng** [comment]
1. go to the php-diff directory (the root dir of this project, not the `example` dir)
2. run `composer install`
3. run `composer run-script server`
4. visit `http://localhost:12388/demo_web.php`

---

Cant you just read the really short readme? Let me read it and type them for you is not fun.

**Comment by jfcherng** [comment]
fwiw, I will re-phrase the example readme since I found it's misleading potentially.

**Comment by unluckychild** [comment]
make standalone without composer pls

**Comment by jfcherng** [comment]
> make standalone without composer pls

do it by yourself. i won't go back as composer is the de facto standard.

**Comment by unluckychild** [comment]
it is annoying for users on shared hostings

**Comment by jfcherng** [comment]
> it is annoying for users on shared hostings

that's not my problem, i am going to unsubscribe this issue as it no longer related to this lib. this lib is open source, just do whatever you want to do without breaking the license.

**Comment by unluckychild** [comment]
well, after installing composer i ended up deleting 5500 not needed files.
