### ISSUE TITLE
Argument 1 passed to Jfcherng\Diff\Differ::setOldNew() must be of the type array, null given

### ISSUE THREAD

**Issue by galiganu** [jfcherng/php-diff#48]
Hi

There is an issue when one of the string is null:
```
Uncaught TypeError: Argument 1 passed to Jfcherng\Diff\Differ::setOldNew() must be of the type array, null given, called in ./vendor/jfcherng/php-diff/src/DiffHelper.php on line 141 and defined in ./vendor/jfcherng/php-diff/src/Differ.php:140
```

Thanks
galiganu

**Comment by jfcherng** [comment]
Unless you provide more details for how to trigger that issue otherwise there is no way to fix it.

**Comment by galiganu** [comment]
Sorry, I thought it was clear :).
The error appears when one of the strings is null.

**Comment by jfcherng** [comment]
If you do mean `There is an issue when one of the string is null`, then this is a non-issue. `null` is not `array` or `string` for sure. The error message is pretty clear too.

**Comment by jfcherng** [comment]
If you are using the diff helper, check its PHP doc.
https://github.com/jfcherng/php-diff/blob/8fef34a4fbd9c12b6b44a62ec303b9f4703ca3e6/src/DiffHelper.php#L115-L125
Or, you need a better IDE or editor to do it for you.

**Comment by galiganu** [comment]
This was clear :)
I just thought that maybe a check if the string is null can be added.
I will add it on my side.

Thanks!
