### ISSUE TITLE
Question: PHP8 Support

### ISSUE THREAD

**Issue by stathisgeo** [jfcherng/php-diff#52]
Hello,

Is the package compatible with php8? I see the tests are running on php8.1 too but I would like to see if anyone is using it in php8 env.

**Comment by jfcherng** [comment]
I personally use this package on PHP 8.0 and previously I ran it on PHP 7.4. I think it should auto work for recently future PHP since I avoid using deprecated things but untested.

**Comment by stathisgeo** [comment]
It is working fine for me on PHP 8.0.8, I was just looking for some verification, so thank you for the response @jfcherng.
