### ISSUE TITLE
Difference is not rendering properly for 'Combined' rendered

### ISSUE THREAD

**Issue by AshishDhamalaAD** [jfcherng/php-diff#56]
Thank you for making such an awesome package. It's really useful.
I was trying this package today and found one issue when rendering output to the HTML. That's why I am creating an issue here.

### Old file
Path:
```
/folder/old.txt
```

Content:
```
This is the old file.
This is the line that is not changed.
I am writing here in the old file.
```

### New file
Path:
```
/folder/new.txt
```

Content:
```
This is the new file.
This is the line that is not changed.
I am writing here in the new file.
```

### What I did
The code that I ran is this. It's the same example from the readme.

```php
$rendererName = 'Combined';
$old = file_get_contents("/folder/old.txt");
$new = file_get_contents("/folder/new.txt");

$jsonResult = DiffHelper::calculate($old, $new, 'Json');
$htmlRenderer = RendererFactory::make($rendererName);
$output = $htmlRenderer->renderArray(json_decode($jsonResult, true));
```

When rendering the output to the browser, it looks like this:
<img width="1392" alt="Screen Shot 2022-06-26 at 4 25 49 AM" src="https://user-images.githubusercontent.com/65481305/175798113-c87644b7-dcfe-41c4-a100-f7ca5e391807.png">

But the other `$rendererName` options works perfectly fine. For example `Inline`
<img width="1429" alt="Screen Shot 2022-06-26 at 4 27 25 AM" src="https://user-images.githubusercontent.com/65481305/175798147-e6475943-78ee-4c26-a92c-422bfaf6feaa.png">

**Comment by jfcherng** [comment]
Thanks. Fixed in just released `6.11.6`.
