### ISSUE TITLE
tabs and spaces

### ISSUE THREAD

**Issue by brianteeman** [jfcherng/php-diff#58]
What is the intended behaviour of the tab visualisation you show in the demo. Doesnt appear to do anything.

In my tests I have set 6 spaces and two tabs

    'spacesToNbsp' => true,
    'tabSize' => 4,

![image](https://user-images.githubusercontent.com/1296369/191355150-bef45b4c-44f5-4384-b0b7-f58af516eea5.png)

![image](https://user-images.githubusercontent.com/1296369/191355767-59419fc0-099e-463c-92df-5e7771bf4742.png)

it looks to me that only every alternative space is being presented as a nbsp

am I misunderstanding something?

**Comment by jfcherng** [comment]
> What is the intended behaviour of the tab visualisation you show in the demo. Doesnt appear to do anything.

As the comment of 
```php
    // the frontend HTML could use CSS "white-space: pre;" to visualize consecutive whitespaces
    // but if you want to visualize them in the backend with "&nbsp;", you can set this to true
    'spacesToNbsp' => false,
```

, if you remove `white-space: pre-wrap;` from CSS with `'spacesToNbsp' => false,`, then all consecutive whitespaces are folded into a single one visually on the browser.

**Comment by brianteeman** [comment]
i guess I was expecting 6 spaces to be coded as 6 &nbsp and I was hoping to visually represent the &nbsp with a • and a tab with ⇥ or similar but its not possible without a one to one transposition of space and nbsp

but if this is as intended then thats fine. Feel free to close

**Comment by jfcherng** [comment]
> i guess I was expecting 6 spaces to be coded as 6 &nbsp and I was hoping to visually represent the &nbsp with a • and a tab with ⇥ or similar but its not possible without a one to one transposition of space and nbsp

This sounds like a valid feature request.


![image](https://user-images.githubusercontent.com/6594915/191436642-0dd0e791-225b-4e20-a451-12d2b81589bf.png)

GitHub does it like the above with a background image for those DOMs via CSS btw. That way seems to be less intrusive and customizable.

**Comment by brianteeman** [comment]
yes thatds exactly what I was looking for.

Codemirror does something similar as well.

PS I am submitting a pr shortly that will prevent the selecting of the line number and the + -

**Comment by brianteeman** [comment]
If we could convert spaces and tabs to
```
<span class="space"></span><span class="space"></span>
<span class="tab"></span>
```

Then it could be displayed as
![image](https://user-images.githubusercontent.com/1296369/191464270-42d35a8b-673c-479c-9c05-44e6ab337abe.png)

This would be especially useful when the diff is showing a conversion from tab to spaces indentation etc.

**Comment by jfcherng** [comment]
Could you test https://github.com/jfcherng/php-diff/pull/60?
