### ISSUE TITLE
Different Line of text not comparing

### ISSUE THREAD

**Issue by mk-bala** [jfcherng/php-diff#6]
Hi,

I am trying to compare old text 5 lines and new text 10 lines but the script not return any comparison results. its show no difference. please advice can compare different number of lines both side?

**Comment by jfcherng** [comment]
First you have to let other people reproduce your case otherwise they(me) are lazy to figure it out. So, I would advise that you provide example codes and inputs.

**Comment by mk-bala** [comment]
Hi,

Thanks for your quick reply. i am using below code to get the different. but below one not return any difference it says no difference. if i delete test1 and test2 from the $old it shows the difference. Please advice if i miss anything?

$old = "test
             test1
             test2";
$new = "test123";

 // renderer class name: Unified, Context, Json, Inline, SideBySide
        $rendererName = 'SideBySide';
 $result = DiffHelper::calculate($old, $new, $rendererName);

**Comment by jfcherng** [comment]
I still can't reproduce the problem with the latest v6 so I have some questions.

- What PHP version are you using?
- What `jfcherng/php-diff` version are you using?

**Comment by mk-bala** [comment]
Hi,
i am using PHP 7.2 and jfcherng/php-diff V6

**Comment by jfcherng** [comment]
I still cannot reproduce it with PHP 7.2.18 and v6.0.0. I would suggest that you provide the full (but simple) example as either a git repository or code blocks.

**Comment by mk-bala** [comment]
Hi,

Here is my code 

 $old = "test\n test1";
        $new = "test";
        $rendererName = 'SideBySide';
        echo $result = DiffHelper::calculate($old, $new, $rendererName);

out put for this:
<table class="diff diff-html diff-side-by-side"><thead><tr><th colspan="2">Old</th><th colspan="2">New</th></tr></thead><tbody class="change change-eq"><tr><th class="n-old">1</th><td class="old">test</td><th class="n-new">1</th><td class="new">test</td></tr></tbody><tbody class="change change-del"><tr><th class="n-old">2</th><td class="old"> test1</td><th></th><td class="new"></td></tr></tbody></table>

$old = "test\n test1";
        $new = "test\n test2";
        $rendererName = 'SideBySide';
        echo $result = DiffHelper::calculate($old, $new, $rendererName);

out put for this:
<table class="diff diff-html diff-side-by-side"><thead><tr><th colspan="2">Old</th><th colspan="2">New</th></tr></thead><tbody class="change change-eq"><tr><th class="n-old">1</th><td class="old">test</td><th class="n-new">1</th><td class="new">test</td></tr></tbody><tbody class="change change-rep"><tr><th class="n-old">2</th><td class="old"><span> test<del>1</del></span></td><th class="n-new">2</th><td class="new"><span> test<ins>2</ins></span></td></tr></tbody></table>

the second one output is correct the first one somehow not comparing the text.

**Comment by jfcherng** [comment]
It does compare in your first example. The HTML element `tbody.change.change-del` implies the whole line is deleted. You have to either use the CSS in the demo (`example/diff-table.css`) or write your own.

**Comment by mk-bala** [comment]
Hi,

Thanks for your help. it seems some issue with the diff-table.scss somehow not working for me inow i have changed to diff-table.css it works fine.

Thanks again
