### ISSUE TITLE
get just the different words?

### ISSUE THREAD

**Issue by danielzzz** [jfcherng/php-diff#61]
hi, I am wondering if it's possible to just show the different words, for example:

```
$s1 = "hello Alice";
$s2 = "hello John";

// diff would show just Allice | John not the full line
```

I tried using detailLevel=>'word' but it doesn't seem to have this effect

thanks!
dan

**Comment by jfcherng** [comment]
I am not sure what you mean exactly but sounds like a non-goal.

**Comment by danielzzz** [comment]
Right now, I am getting this as the result:

```
"[[{"tag":8,"old":{"offset":0,"lines":["hello Dan"]},"new":{"offset":0,"lines":["hello Peter"]}}]]"
```

but I would like just to know that the differences are "Dan" and "Peter" not the whole "hello Dan" and "hello Peter"

is it possible here?

thanks, dan

**Comment by jfcherng** [comment]
You may use the `JsonHtml` renderer with word-level details: https://github.com/jfcherng/php-diff/blob/v6/README.md#renderer-html-json

So things in `<del>...</del>` is deleted and `<ins>...</ins>` is added. Do notice that contents are HTML encoded. That is, if `<` gets deleted, it will be `<del>&lt;</del>`.

**Comment by danielzzz** [comment]
ok, thanks, this might help!
