### ISSUE TITLE
Loss of whitespace in combined view with newlines

### ISSUE THREAD

**Issue by etaunknown** [jfcherng/php-diff#68]
A very minor style update that was introduced from this issue: https://github.com/jfcherng/php-diff/issues/34

Reversing the [commit](https://github.com/jfcherng/php-diff/commit/35a250235f4224b89b951605f079d7aa3c184f26) resolved the issue, although I couldn't follow what the parent issue was and I may be overlooking some config setting using it for the first time.

```
      $rendererName = 'Combined';
      $old = <<<END
parent:
  title: Title
  restrict: true
  callback: true
  url: /demo
  modified: 2023-02-12T07:47:49+10:00
  published: 2020-07-29T10:39:04+10:00
END;
      $new = <<<END
parent:
  title: Title
  restrict: true
  callback: true
  url: /demo
  modified: 2022-05-13T11:05:52+10:00
  published: 2020-07-29T10:39:04+10:00
END;
      $result = DiffHelper::calculate($old, $new, $rendererName);
      print '<div style="border: 1px solid #333; border-radius: 5px; background-color: #eee;">' . $result . '</div>';
```

![screenshot-diff](https://user-images.githubusercontent.com/32726262/221510609-5d204338-6002-48df-b2e4-4da74288c2fd.png)

As an aside, great job forking the old project, it was good to finally to be able to update this project :)

**Comment by jfcherng** [comment]
Thanks. I revert that commit and fix it in another way. `6.13.1` has been released.
