### ISSUE TITLE
Autoloader tries to include Html/Unified.php

### ISSUE THREAD

**Issue by timint** [jfcherng/php-diff#77]
I have a problem with rendererName `Unified` calling for Jfcherng/Diff/Renderer/Html/Unified.php but the file is in the Text folder, not Html.

```
include 'vendor/autoload.php';
$diff = Jfcherng\Diff\DiffHelper::calculate($string1, $string2, 'Unified'); // Nope
```

It's worth noting I have a secondary spl_autoloader that fires if Composer's was unable to include the file. This is where I caught it. It shouldn't interfere as the secondary autoloader only fires when Composer did not autoload.

**Comment by jfcherng** [comment]
since CI didnt fail on GitHub, I assume it's your setup.

**Comment by jfcherng** [comment]
I would suggest provide a minimal reproducible repository.

**Comment by jfcherng** [comment]
Related code should be https://github.com/jfcherng/php-diff/blob/e0da9862792cc176160781871cfdcc2547984fa9/src/Factory/RendererFactory.php#L54-L76 but I don't see how it can fail.

**Comment by jfcherng** [comment]
Oh, https://github.com/jfcherng/php-diff/blob/e0da9862792cc176160781871cfdcc2547984fa9/src/Factory/RendererFactory.php#L67-L73 will try `Html` first and then try `Text`. So I guess it's that why your autoloader emits an error. But then that sounds like a wrong implementation in your autoloader. It should include a file only if it exists.

Would `class_exists('NonExistingClass')` emits an error in your autoloader? 🤔

**Comment by timint** [comment]
Yes, but class_exists('NonExistingClass', false) would work. class_exists() defaults to passing it to the autoloader when the 2nd parameter is omitted or true. And when there is no such class returned from Composer, it's passed down to the next registered spl autoloader.

Using is_file() instead of class_exist() could be a solution.

**Comment by jfcherng** [comment]
> Using is_file() instead of class_exist() could be a solution.

Yes, but it should be done in your autoloader before you `include` it. `class_exists` should not cause any error.

**Comment by timint** [comment]
Ok. Is this to enable some plug n play file behavior that you are using class_exist() to determine if files are present or not? Otherwise an enumerated list would prevent it from escalating further up the chain of processes. This is the first time I had a Composer library trigger a secondary autoloader. Not a big deal now that I know the cause, and how to get around it. But thought I would provide the feedback.

While I have you on the line. Can this library perform the patching of a string or file as well? I have the understanding I need another library for that.

**Comment by jfcherng** [comment]
> While I have you on the line. Can this library perform the patching of a string or file as well? I have the understanding I need another library for that.

No, this lib doesn't support patch. If you need patch, maybe https://packagist.org/packages/diff/diff but I didn't try.

> Ok. Is this to enable some plug n play file behavior that you are using class_exist() to determine if files are present or not? Otherwise an enumerated list would prevent it from escalating further up the chain of processes. This is the first time I had a Composer library trigger a secondary autoloader. Not a big deal now that I know the cause, and how to get around it. But thought I would provide the feedback.

My point would be `class_exists` shouldn't emit an error but return a boolean. If your autoloader implementation make it emit an error, I don't think that's my fault or I should modify something.

**Comment by timint** [comment]
Thank your looking into this and providing feedback.
