### ISSUE TITLE
Render identical strings instead of returning null

### ISSUE THREAD

**Issue by mansoorkhan96** [jfcherng/php-diff#78]
First of all, Thank you so much for working on this amazing package ❤️

I am working on a Versioning plugin that shows the diff for fields like title, content.

Its inspired by WordPress Revisioning system.

Is there any option in this package to render the identical strings as they are instead of returning null. Just like WordPress, it renders both the string as they were not changed.

Here is work around we are using in a package:

```php
if ($old === $new) {
    $diff[$key] = '<table class="diff-wrapper diff diff-html diff-side-by-side"><tbody class="change change-eq"><tr><td class="old">'.$old.'</td><td class="new">'.$new.'</td></tr></tbody></table>';
} else {
    $diff[$key] = str_replace('\n No newline at end of file', '', DiffHelper::calculate($old, $new, $renderer, $differOptions, $renderOptions));
}
```

Default behaviour of the package is fine. But i wish there is a way to render above by passing a render option maybe?

**Comment by jfcherng** [comment]
Could you try PR #79 ?

Just set `fullContextIfIdentical` to `true` in differ options.

**Comment by mansoorkhan96** [comment]
> Could you try PR #79 ?
> 
> Just set `fullContextIfIdentical` to `true` in differ options.

@jfcherng wow man that was quick. I will check in a few.

TYSM.

**Comment by mansoorkhan96** [comment]
> Could you try PR #79 ?
> 
> Just set `fullContextIfIdentical` to `true` in differ options.

Works like a charm! Thanks

<img width="740" alt="image" src="https://github.com/jfcherng/php-diff/assets/51432274/5a5d05db-eb36-47c2-942e-02f4d089f314">

**Comment by jfcherng** [comment]
`v6.16.0` / `v6.10.15` have been released.
