### ISSUE TITLE
how to display both file entirely with difference like Beyond compare 

### ISSUE THREAD

**Issue by infuginindia** [jfcherng/php-diff#8]
Hi,
How to display both file entirely with difference like Beyond compare.

Entire code of file name in left side and entire code of file 2 on right side, and
difference highlighted.

Thanks in advance.
Arvind

**Comment by jfcherng** [comment]
> Entire code of file name in left side and entire code of file 2 on right side, and difference highlighted.

set the `context` with a large enough number?

![image](https://user-images.githubusercontent.com/6594915/64003880-cf21fc80-cb3f-11e9-99c2-d1e5d1b29b0b.png)

**Comment by infuginindia** [comment]
Thank you Jfcherng
