### ISSUE TITLE
Is it possible to get a simple diff count containing only +-int

### ISSUE THREAD

**Issue by mansoorkhan96** [jfcherng/php-diff#80]
Is it possible to only get the diff count for two string?

**Example 1:**
text1: foo
text2: bar

diff: [
'-' => 3
'+' => 3
]

**Example 1:**
text1: foo
text2: foo bar

diff: [
'-' => 0
'+' => 4
]

**Comment by jfcherng** [comment]
You can call https://github.com/jfcherng/php-diff/blob/26f93d793b68ae640413b5330c5726f51078d68c/src/Differ.php#L273-L280

or in case you are using the DiffHelper, which uses the singleton pattern.
https://github.com/jfcherng/php-diff/blob/26f93d793b68ae640413b5330c5726f51078d68c/src/DiffHelper.php#L109-L112

**Comment by mansoorkhan96** [comment]
I have tried following but i am getting an error:

```php
$differ = new Differ($oldContents, $newContents, $differOptions);
dd($differ->getStatistics());
```

https://flareapp.io/share/dPbaqjNm

<img width="1337" alt="image" src="https://github.com/jfcherng/php-diff/assets/51432274/34e22ebe-d550-4b6e-9fa6-42e34af67095">

**Comment by jfcherng** [comment]
I need an exact reproducible $oldContents, $newContents, $differOptions.

**Comment by mansoorkhan96** [comment]
> I need an exact reproducible $oldContents, $newContents, $differOptions.

Oh yes, sure thing. Just give me some time.

**Comment by mansoorkhan96** [comment]
```php
$differ = new Differ(
    [
        'title' => 'An Example Article',
        'content' => '# Filament Versionable

A Filament plugin and a wrapper around [Laravel Versionable](https://github.com/overtrue/laravel-versionable) to create versions Laravel Models. When ever you save a model, it would store the specified `$versionable` fields to the Database and then you can revert to any target model state any time.',
    ],
    [
        'title' => 'An Example Article',
        'content' => '# Filament Versionable

A Filament plugin and a wrapper around [Laravel Versionable](https://github.com/overtrue/laravel-versionable) to store versions for Laravel Models. When ever you save a model, it would store the specified `$versionable` fields to the Database and then you can revert to any target model state any time.',
    ],
    ['fullContextIfIdentical' => true]
);

$differ->getStatistics();
```

**Comment by jfcherng** [comment]
The constructor of `Differ` accepts $old, $new as `array of string`.
https://github.com/jfcherng/php-diff/blob/26f93d793b68ae640413b5330c5726f51078d68c/src/Differ.php#L120-L127

But I do find something that I have to fix.

**Comment by jfcherng** [comment]
A new release has been published to fix what I found. But the issue you have is passing old/new in a wrong form. The correct form is like `$old = ['line 1', 'line 2', 'line 3'];`.

**Comment by mansoorkhan96** [comment]
Alright, I have changed the array structure but it always returns the same output:
Output: array:4 [
  "inserted" => 1
  "deleted" => 1
  "unmodified" => 1
  "changedRatio" => 0.5
]

Here is the input to reproduce:

```php
$differ = new Differ(
            ['An Example Article', '# Filament Versionable

A Filament plugin and a wrapper around [Laravel Versionable](https://github.com/overtrue/laravel-versionable) to store versions for Laravel Models. When ever you save a model, it would store the specified `$versionable` fields to the Database and then you can revert to any target model state any time.

Wire Extender allows you to embed any Livewire component on any website or even within a static HTML file.

# Lorem Ipsum

Lorem ipsum dolor sit amet, consectetur adipiscing elit. In venenatis ac ante ut convallis. Sed blandit eu mauris quis cursus. Phasellus ultrices pretium enim in semper. 

Maecenas porttitor dolor tellus. Proin a mattis lectus. Proin vitae nunc luctus, accumsan ipsum vel, iaculis augue. Donec eget euismod diam. 

Lorem ipsum dolor sit amet, consectadsetur adipiscing elit. In venenatis ac ante ut convallis. Sed blandit eu mauris quis cursus. Phasellus ultradsfices pretium enim in semper. Maecenas porttitor dolor tellus. Proin a mattis lectuadsfs. Proin vitae nunc luctus, accumsan ipsum vadsfel, iaculis augue. Donec eget euismod diam.'],
            ['An Example Article', '# Filament Versionable

A Filament plugin and a wrapper around [Laravel Versionable](https://github.com/overtrue/laravel-versionable) to store versions for Laravel Models. When ever you save a model, it would store the specified `$versionable` fields to the Database and then you can revert to any target model state any time.'],
            ['fullContextIfIdentical' => true]
        );
```

**Comment by mansoorkhan96** [comment]
Or do i need to split the actual string, and then pass it as array?

**Comment by mansoorkhan96** [comment]
Ah yes, this works.

```php
$differ = new Differ(
    ['line 1', 'line 2', 'line 3'],
    ['line one', 'line two', 'line three'],
    ['fullContextIfIdentical' => true]
);
```

**Comment by jfcherng** [comment]
> Or do i need to split the actual string, and then pass it as array?

That depends on your need. Each elements in the array will be treated as a whole. It's just usually people want to know how many lines are different by minimal edits but in your previous codes, it's more like telling how many articles are different.

**Comment by mansoorkhan96** [comment]
Alright, Thanks.

Here is what works for me:

```php
// I run this code in a loop.

$diffStats[] = (new Differ(
    explode("\n", $oldContents[$key]),
    explode("\n", $newContents[$key]),
))->getStatistics();
```

And then do sum.
