### ISSUE TITLE
Remove var_dump

### ISSUE THREAD

**Issue by mansoorkhan96** [jfcherng/php-diff#81]
Hi, real quick,

Could you please remove var_dump over here. I was pulling my hear out wondering what i did wrong LOL.

https://github.com/jfcherng/php-diff/blob/0a0f50a6da233bc86d105bcfa4efc302e5d6c2fc/src/Differ.php#L293

**Comment by mansoorkhan96** [comment]
Architecture Testing can help us avoid such typos. Not sure if something like this exists in PHPUnit.

https://pestphp.com/docs/arch-testing#content-tobeused

Thanks ❤️

**Comment by jfcherng** [comment]
Done. oops

**Comment by jfcherng** [comment]
Fixed and released.

**Comment by mansoorkhan96** [comment]
Thanks.

**Comment by mansoorkhan96** [comment]
Your package has been very helpful to let me build an awesome plugin.

<img width="1349" alt="image" src="https://github.com/jfcherng/php-diff/assets/51432274/4d28156b-2070-4113-b5e8-fecc23b25965">
