### ISSUE TITLE
unexpected combined diff result with Chinese

### ISSUE THREAD

**Issue by void285** [jfcherng/php-diff#82]
Hi, this maybe a problem, different test strings lead to different results.

```php
    $rendererOptions = [
        'detailLevel' => 'char',
        'lineNumbers' => true,
        'showHeader' => false,
        'spacesToNbsp' => false,
        'tabSize' => -1,
        'separateBlock' => true,
        'resultForIdenticals' => '=',
        'wrapperClasses' => [],
    ];
    $differOptions = [];
    $rendererName = 'Combined';
    $old = '手动风尚打破';
    $new = '啊阿斯蒂芬破';
    // or
    // $old = '破手动风尚打';
    // $new = '破啊阿斯蒂芬';
    $diff_result = DiffHelper::calculate($old, $new, $rendererName, $differOptions, $rendererOptions);
```

expected: `<del>手动风尚打</del><ins>啊阿斯蒂芬</ins>破`
got `<del>手动风尚打</del>破<ins>啊阿斯蒂芬</ins>破`

or

expected: `破<del>手动风尚打</del><ins>啊阿斯蒂芬</ins>`
got: `破<del>手动风尚打</del>破<ins>啊阿斯蒂芬</ins>`

conditions to reproduce:
```
中文
字数相同
字数>=6
首字相同或尾字相同
```

```
chinese
old and new string with same length
length >= 6
same head or tail char
```

**Comment by jfcherng** [comment]
I can't reproduce that. 

![image](https://github.com/jfcherng/php-diff/assets/6594915/622266c5-150d-43ed-be78-4f07cf4b211e)

The only thing I can suspect at this moment is that you are using an alpine docker image. Something weird happened before with its `iconv` extension. Ref: https://github.com/jfcherng/php-diff/issues/51

**Comment by void285** [comment]
Sorry, it may be caused by my preg_replace function:
when compare 破手动风尚 vs 破啊阿斯蒂:
the result is `<tr data-type="!"><td class="rep">破<del>手动风尚</del><ins>啊阿斯蒂</ins></td></tr>`
when compare 破手动风尚打 vs 破啊阿斯蒂芬:
the result is `<tr data-type="-"><td class="old">破<del>手动风尚打</del></td></tr><tr data-type="+"><td class="new">破<ins>啊阿斯蒂芬</ins></td></tr>`

It seems when string length >= 6 or something, the result format is diffrent.

I didn't notice the tr type and only deal with the tds in a wrong way. I will expore more tomorrow. What I want to do is to produce result with same format as https://github.com/kpdecker/jsdiff

**Comment by jfcherng** [comment]
> when compare 破手动风尚 vs 破啊阿斯蒂:
> the result is `<tr data-type="!"><td class="rep">破<del>手动风尚</del><ins>啊阿斯蒂</ins></td></tr>`
> when compare 破手动风尚打 vs 破啊阿斯蒂芬:
> the result is `<tr data-type="-"><td class="old">破<del>手动风尚打</del></td></tr><tr data-type="+"><td class="new">破<ins>啊阿斯蒂芬</ins></td></tr>`

Looks like you want to always merge/combine the difference, then set this to `1`.
https://github.com/jfcherng/php-diff/blob/58e515035f588eecc44f4a0ad85838cd1069b129/src/Renderer/AbstractRenderer.php#L79-L82


> I didn't notice the tr type and only deal with the tds in a wrong way. I will expore more tomorrow. What I want to do is to produce result with same format as [kpdecker/jsdiff](https://github.com/kpdecker/jsdiff)

I am not sure whether creating your own Renderer implementation is an easier choice.

**Comment by void285** [comment]
> Looks like you want to always merge/combine the difference, then set this to 1.

Thank you, I got what expected, this really helps a lot!
