### ISSUE TITLE
unexpected combined diff result with repeat parts

### ISSUE THREAD

**Issue by void285** [jfcherng/php-diff#83]
Hi, I'm not sure if this is algorithm design or not, but the result is not somehow plain or straightforward.

```
    $rendererOptions = [
        'detailLevel' => 'char',
        'lineNumbers' => true,
        'showHeader' => false,
        'spacesToNbsp' => false,
        'tabSize' => -1,
        'mergeThreshold' => 1,
        'separateBlock' => true,
        'resultForIdenticals' => '=',
        'wrapperClasses' => [],
    ];
    $differOptions = [];
    $rendererName = 'Combined';
    $old = '更附堯佐史附堯佐';
    $new = '史附堯佐|史附堯佐';
    $diff_result = DiffHelper::calculate($old, $new, $rendererName, $differOptions, $rendererOptions);
```

expected (1st line in img): `<del>更</del><ins>史</ins>附堯佐<ins>|</ins>史附堯佐`
got (2nd line in img): `<del>更附堯佐</del>史附堯佐<ins>|史附堯佐</ins>`

![image](https://github.com/jfcherng/php-diff/assets/612912/fb56f0e8-b0e6-41d1-a529-de92a32799e5)

I also test `old=Abcabc and new=abc-abc`, got same result.

**Comment by jfcherng** [comment]
I wont be able to aceess my PC for days due to Chinese holiday. It looks like a suboptimal result in this case but I probably wont fix it (or I dont really care) since it is still a correct result. I welcome a PR though if it's not too complicated. The package to fix would be the sequence matcher.

**Comment by jfcherng** [comment]
What if you swap old and new?

**Comment by void285** [comment]
I will explore more about it.

Result when swap old and new:

`<ins>更附堯佐</ins>史附堯佐<del>|史附堯佐</del>`

![image](https://github.com/jfcherng/php-diff/assets/612912/fcc8ebf1-f202-4b7f-97e9-8d0089f6a892)

**Comment by jfcherng** [comment]
Since the sequence matcher is ported from Python's standard difflib. I would say it's working as expected.

![image](https://github.com/jfcherng/php-diff/assets/6594915/74887482-8b7a-478d-9514-d2b00c38f5ba)

---

```py
import difflib

tesecases = [
    ("更附堯佐史附堯佐", "史附堯佐|史附堯佐"),
]

for old, new in tesecases:
    print(f"{old} => {new}")
    for i, (sign, _, char) in enumerate(difflib.ndiff(old, new)):
        match sign:
            case "-":
                print(f'Delete "{char}" from position {i}')
            case "+":
                print(f'Add "{char}" to position {i}')
    print("-" * 60)
```

**Comment by void285** [comment]
Thanks, I dont realize it works the same way as difflib, indeed defferent strategy produce different results, and the results are acceptable.
