### ISSUE TITLE
display data in html format

### ISSUE THREAD

**Issue by infuginindia** [jfcherng/php-diff#9]
Hi ,

Is there any way to display data in html like it shows on a web page.

it must render data as html , img src must display image not the image code.

Thanks
Arvind

**Comment by infuginindia** [comment]
I am using side by side and have saved data in txt files, or can I use Side by Side without storing data in txt file

**Comment by jfcherng** [comment]
> or can I use Side by Side without storing data in txt file

In README.

```php
// one-line simply compare two strings
$result = DiffHelper::calculate($old, $new, $rendererName, $differOptions, $rendererOptions);
```

> Is there any way to display data in html like it shows on a web page.

I cannot understanding this as the default behavior of this lib is allowed them to be shown in HTML already. And `SideBySide` must be HTML.

**Comment by infuginindia** [comment]
I have used ckeditor to store html in mysql database, for sidebyside  I have store data in txt files , even in html file.

have a look of output
http://prntscr.com/ozwfgc

with SideBySide this is not working 

// one-line simply compare two strings
$result = DiffHelper::calculate($old, $new, $rendererName, $differOptions, $rendererOptions);

**Comment by jfcherng** [comment]
So in your definition of "not woking", is the screenshot not working?

If yes, to make the problem even more clear, what's wrong with the screenshot?

**Comment by infuginindia** [comment]
the data is not displaying as html like given below.

http://prntscr.com/ozxdib
http://prntscr.com/ozxdsl
http://prntscr.com/ozxe3g

I want html to be rendered as html not the text

**Comment by jfcherng** [comment]
> the data is not displaying as html like given below.

That's expected behavior.

If they display like those 3 screenshots, it's a bug.

**Comment by infuginindia** [comment]
no these screenshots are not from this library, I want output as shown in screenshots, is this possible ?

**Comment by jfcherng** [comment]
Probably not because currently this lib treat all inputs as plain text. So, consider the following case:

- old:
  ```html
  <p>
  hi
  <p>
  ```
- new: 
  ```html
  <span>
  hi
  </span>
  ```

It will only knows

```diff
-<p>
+<span>
 hi
-</p>
+</span>
```

but not


```diff
-<p>
-hi
-</p>
+<span>
+hi
+</span>
```

**Comment by infuginindia** [comment]
Thanks , i will try if found any solution or any other library to achieve it,

**Comment by hasan-ozbey** [comment]
that kind of functionality could lead us to vulnerable for XSS attacks
